In [1]:
# Step1. NumPyをインポートするコードを記述する
import numpy as np

# Step2. AとBの行列を格納する多次元配列のコードを記述する
A = np.array([[0, 1], [2, 3], [4, 5]])
B = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])

# Step3. 行列の積の計算をするコードを記述する
result = np.dot(A, B)

# Step4. Step3.の計算結果を表示するコードを記述する
print("行列の積の計算結果:")
print(result)

# Step5. 行列の要素の最大値を求めるコードを記述する
max_value = np.max(result)
print("計算された行列の要素の最大値:", max_value)


行列の積の計算結果:
[[ 4  5  6  7]
 [12 17 22 27]
 [20 29 38 47]]
計算された行列の要素の最大値: 47
